export const HERO_MOVIES = [
  'The Dark Knight',
  'Iron Man',
  'Wonder Woman',
  'Spider-Man: Into the Spider-Verse',
  'The Avengers',
  'Captain America: The Winter Soldier',
  'Black Panther',
  'Thor: Ragnarok',
  'Guardians of the Galaxy',
  'Deadpool',
  'Doctor Strange',
  'Man of Steel',
  'Captain Marvel',
  'Batman Begins',
  'X-Men: Days of Future Past',
  'Ant-Man',
  'Aquaman',
  'Avengers: Infinity War',
  'Logan',
  'The Incredibles',
  'Hellboy',
  'The Dark Knight Rises',
  'Iron Man 3',
  'Thor',
  'The Amazing Spider-Man',
  'Wonder Woman 1984',
  'Spider-Man: Homecoming',
  'Black Widow',
  'Guardians of the Galaxy Vol. 2',
  'Deadpool 2',
  'Doctor Strange in the Multiverse of Madness',
  'Superman Returns',
  'Thor: The Dark World',
  'Captain America: Civil War',
  'Black Panther: Wakanda Forever',
  'X-Men: First Class',
  'Ant-Man and The Wasp',
  'Aquaman and the Lost Kingdom',
  'Avengers: Endgame',
  'Logan: The Wolverine',
  'The Incredibles 2',
  'Hellboy II: The Golden Army',
  'The Dark Knight Rises',
  'Iron Man 2',
  'Thor: The Dark World',
  'The Amazing Spider-Man 2',
  'Wonder Woman 1984',
  'Spider-Man: Far From Home',
  "Black Widow: Widow's Sting",
  'Guardians of the Galaxy Vol. 3',
  'Deadpool 3',
  'Doctor Strange in the Multiverse of Madness',
  'Superman and Lois',
  'Thor: Love and Thunder',
  'Captain America: The First Avenger',
  'Black Panther: Wakanda Forever',
  'X-Men Origins: Wolverine',
  'Ant-Man and The Wasp: Quantumania',
  'Aquaman and the Lost Kingdom',
  'Avengers: Endgame',
  'Logan: The Wolverine',
  'The Incredibles 2',
  'Hellboy II: The Golden Army'
];
